---
# Usuario gen√©rico para ejecutar algunas tareas
remote_regular_user: "{{ ansible_env.SUDO_USER }}"

rancher2_version: "v2.6.0"

vscode_extension_list:
  # Install Visual Studio Code extensions.
  - ms-python.python
  # Markdown linting and style checking for Visual Studio Code
  - DavidAnson.vscode-markdownlint
  # Makes it easy to create, manage, and debug containerized applications.
  - ms-azuretools.vscode-docker
  # Beautify code in place for VS Code
  - HookyQR.beautify
  # Automatically add HTML/XML close tag, same as Visual Studio IDE or Sublime Text
  - formulahendry.auto-close-tag
  ## Muestra en rojo los espacios inutilziados
  - shardulm94.trailing-spaces
  # Highlight CSV and TSV files, Run SQL-like queries
  - mechatroner.rainbow-csv
  # Provides path completion
  - ionutvmi.path-autocomplete
  # XML Tools for Visual Studio Code
  - dotjoshjohnson.xml
  # Supercharge the Git capabilities built into Visual Studio Code
  - eamodio.gitlens
  # Odoo snippets
  - mstuttgart.odoo-snippets
  # Icons
  - pkief.material-icon-theme
  # Share vs (remote)
  - ms-vsliveshare.vsliveshare
  # Check spell (En & Es)
  - streetsidesoftware.code-spell-checker
  - streetsidesoftware.code-spell-checker-spanish
  # Reload plugin
  - natqe.reload
  # Git Visualizer
  - mhutchie.git-graph
  # GitHub Copilot
  - github.copilot
